import { Spacer } from '@chakra-ui/react';
import React from 'react';
import * as PropTypes from 'prop-types';
import Row from '../shared/Row';
import InputLabel from '../shared/texts/InputLabel';
import CurrencyText from '../shared/texts/CurrencyText';

function OperatingIncome({ value }) {
  return (
    <Row>
      <InputLabel tooltipLabel="The total income generated by a property, less the vacancy expense" text="Operating Income" />
      <Spacer />
      <CurrencyText value={value} />
    </Row>
  );
}

OperatingIncome.propTypes = { value: PropTypes.number.isRequired };

export default React.memo(
  OperatingIncome,
  (prevProps, nextProps) => prevProps.value === nextProps.value,
);
